dist: trusty
sudo: required

language: bash

services:
  - docker

env:
  - TARGET=amd64 EXT=""
  - TARGET=amd64 EXT=".local"
  - TARGET=armhf EXT=".armv7-armhf"

matrix:
  exclude:
    - env: TARGET=amd64 EXT=".local"
      if: branch = master
    - env: TARGET=amd64 EXT=""
      if: branch != master
    - env: TARGET=armhf EXT=".armv7-armhf"
      if: branch != master

jobs:
  include:
    - script:
        - docker info
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") -t $DOCKER_REPO:$TRAVIS_BRANCH-$TARGET -f extra/Dockerfile${EXT} .
        - docker run --rm $DOCKER_REPO:$TRAVIS_BRANCH-$TARGET uname -a
        - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
        - docker push $DOCKER_REPO:$TRAVIS_BRANCH-$TARGET
